export enum EVENTS {
  LOGOTYPE_CLICK = "LOGOTYPE_CLICK",
  SEARCH_CLICK = "SEARCH_CLICK",

  READ_MANIFESTO_CLICK = "READ_MANIFESTO_CLICK",
  PARTNER_WITH_US_CLICK = "PARTNER_WITH_US_CLICK",
  ICANN_ACCREDITATION_CLICK = "ICANN_ACCREDITATION_CLICK",

  SUBSCRIBE_CLICK = "SUBSCRIBE_CLICK",
  RESUBSCRIBE_CLICK = "RESUBSCRIBE_CLICK",
  SUBSCRIBE_SUCCESS = "SUBSCRIBE_SUCCESS",
  SUBSCRIBE_ERROR = "SUBSCRIBE_ERROR",

  PRODUCTS_FILTER_CLICK = "PRODUCTS_FILTER_CLICK",
  PRODUCTS_ITEM_CLICK = "PRODUCTS_ITEM_CLICK",

  TRUSTS_FILTER_CLICK = "TRUSTS_FILTER_CLICK",
  TRUSTS_MORE_CLICK = "TRUSTS_MORE_CLICK",
  TRUSTS_ITEM_CLICK = "TRUSTS_ITEM_CLICK",

  COMPANIES_FILTER_CLICK = "COMPANIES_FILTER_CLICK",
  COMPANIES_ITEM_CLICK = "COMPANIES_ITEM_CLICK",
}
